name: hythr
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  flutter_fab_dialer:
    git:
      url: git@github.com:dragonfax/flutter_fab_dialer.git

  image_picker: 0.1.5
  google_sign_in: 1.0.1
  # firebase_analytics: 0.0.4
  firebase_auth: 0.3.1
  firebase_database: 0.1.2
  firebase_storage: 0.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - assets/icons/thin_lines.png
    - assets/icons/thick_lines.png
    - assets/icons/puzzle_piece.png
    - assets/icons/heart.png
    - assets/icons/gradient.png
    - assets/icons/men.png
    - assets/icons/women.png
    - assets/icons/wavy_lines.png
    - assets/icons/looped_line.png
    - assets/icons/straight_line.png
    - assets/icons/lotus.png
    - assets/icons/afro.png
    - assets/icons/dashed_lines.png
    - assets/icons/long_lines.png
    - assets/icons/up_arrow.png
    - assets/icons/wedding_ring.png
    - assets/icons/plusminus.png
    - assets/icons/highlighter.png
    - assets/icons/flame.png
    - assets/icons/scissors.png
    - assets/icons/razor.png
    - assets/images/logo.png
    - assets/images/background.jpg
